# Generated by Django 4.2.23 on 2025-07-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("conteudo", models.TextField()),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                ("autor", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
